version: "3.8"
services:
  data-service:
    build:
      context: ./services/data-service
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgresql://admin:admin@postgres:5432/suppliers
    networks:
      - wp-network
    depends_on:
      - postgres
    command: ["npm", "start"]

  api-service:
    build:
      context: ./services/api-service
    ports:
      - "3002:3002"
    networks:
      - wp-network
    environment:
      - DAPR_HTTP_PORT=3501
      - DAPR_HTTP_HOST=data-service-dapr
    depends_on:
      - data-service
    command: ["npm", "start"]

  data-service-dapr:
    image: daprio/dapr:1.14.4
    command:
      - "./daprd"
      - "--app-id"
      - "data-service"
      - "--app-port"
      - "3001"
      - "--app-channel-address"
      - "data-service"
      - "--dapr-http-port"
      - "3501"
      - "--dapr-grpc-port"
      - "50001"
      - "--config"
      - "/dapr/config/config.yaml"
    ports:
      - "3501:3501"
      - "50001:50001"
    environment:
      - DAPR_HTTP_PORT=3501
      - DAPR_GRPC_PORT=50001
    networks:
      - wp-network
    volumes:
      - ./Dapr:/dapr/config
    depends_on:
      - data-service

  api-service-dapr:
    image: daprio/dapr:1.14.4
    command:
      - "./daprd"
      - "--app-id"
      - "api-service"
      - "--app-port"
      - "3002"
      - "--app-channel-address"
      - "api-service"
      - "--dapr-http-port"
      - "3502"
      - "--dapr-grpc-port"
      - "50001"
      - "--config"
      - "/dapr/config/config.yaml"
    ports:
      - "3502:3502"
      - "50002:50002"
    environment:
      - DAPR_HTTP_PORT=3502
      - DAPR_GRPC_PORT=50002
    networks:
      - wp-network
    volumes:
      - ./Dapr:/dapr/config
    depends_on:
      - data-service

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: suppliers
    ports:
      - "5432:5432"
    networks:
      - wp-network
    volumes:
      - pg-data:/var/lib/postgresql/data

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    networks:
      - wp-network

networks:
  wp-network:
    driver: bridge

volumes:
  pg-data:
